name: "Terraform Pipeline with GitHub Actions"

on:
 workflow_dispatch:
 push:
   branches:
   - main
   paths:
   - ./**

env:
 TF_LOG: INFO

jobs:
 terraform:
   name: "Terraform Pipeline"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: .

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.6.0

     - name: Terraform init
       id: init
       run: terraform init

     - name: Terraform format
       id: fmt
       run: terraform fmt -check

     - name: Terraform validate
       id: validate
       run: terraform validate

     - name: Terraform plan
       id: plan
       run: terraform plan
 
     - name: Terraform Apply
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: terraform apply -auto-approve
       
